// <auto-generated />
namespace Data.EF5.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddSocialLinks_UpdateSubject : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddSocialLinks_UpdateSubject));
        
        string IMigrationMetadata.Id
        {
            get { return "201210242223534_AddSocialLinks_UpdateSubject"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
